### ISSUE TITLE
Wrong character map!

### ISSUE THREAD

**Issue by javadr** [fc7/arabxetex#7]
I'm so confused why the package converts "U+00AB    > U+00BB" and "U+00BB    > U+00AB"!
It causes a bad effect on the output. Let us see an MWE. 

```latex
\documentclass{article}
\usepackage{arabxetex}

\begin{document}

\begin{arab}
        سلام  علیکم ... «مع السلامة» ...
\end{arab}

\end{document}
```
and it will produce the following output. 
![screenshot-20190114135609-470x117](https://user-images.githubusercontent.com/1178221/51107613-84e44900-1804-11e9-8969-d5aa948ec1a5.png)
although, the correct one is something like below:
![screenshot-20190114140004-473x93](https://user-images.githubusercontent.com/1178221/51107692-b8bf6e80-1804-11e9-9d07-70e0e0f64259.png)

**Comment by fc7** [comment]
The mappings in `mirrorpunct.map` should only apply with ArabTeX ASCII input (which is what ArabXeTeX was primarily designed for). When using UTF-8 input, this mapping should ideally be deactivated, but the problem is that arabxetex has no easy way of knowing that. As a workaround, you can load the package with the option `[mirrorpunct=false]` and it should work.

PS: If you only want to input Arabic text with UTF-8 input, you should be fine just by using **polyglosssia** (or **bidi** + **fontspec**). ArabXeTeX will not provide much added value in such cases.
